```{r, eval=FALSE}
install.packages("data.table")
install.packages("ggplot2")
install.packages("devtools")
install.packages("Seurat")
install.packages('network')
devtools::install_github("briatte/ggnet")
install.packages("ggraph")
```

```{r}
library(data.table)
library(ggplot2)
library(ggnet)
```

```{r}
transitions <- fread("~/Desktop/Пасека/transitions.csv", skip = 1, header = F)
transitions <- transitions[,-1]
transitions <- as.matrix(transitions)
rownames(transitions) <- c(1:12)
colnames(transitions) <- c(1:12)
```


```{r}
library(igraph)
library(ggraph)

# build the graph object
network <- graph_from_adjacency_matrix(transitions, weighted = T)

 
# plot it
#plot(network)


#More complicated
ggraph(network) + 
  geom_edge_link(edge_colour="black", edge_alpha=0.3, aes(edge_width=E(network)$weight), arrow = arrow(length = unit(3, 'mm'))) +
  scale_edge_width(range=c(1,3))+
  geom_node_point( color="#69b3a2", size=3)+
  geom_node_text( aes(label=name), repel = TRUE, size=6, color="#69b3a2")+
  theme_void()+
  theme(
    legend.position="none",
    plot.margin=unit(rep(1,4), "cm")
  ) 
```
